{{- if and .Values.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "this.fullname" . }}
  labels: {{- include "this.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ template "this.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  {{- if (not .Values.rbac.useExistingRole) }}
  name: {{ template "this.fullname" . }}
  {{- else }}
  name: {{ .Values.rbac.useExistingRole }}
  {{- end }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
